### ISSUE TITLE
Possibly merge the DLLs for less setup

### ISSUE THREAD

**Issue by FreezyExp** [Thundernerd/Unity3D-NSubstitute#5]
Only referencing 'NSubstitute.dll' gives compile errors.

Using ilmerge https://github.com/dotnet/ILMerge 
the DLLs can be combined into one

which is usually bad practice as it leads to unnecessary bloat, but for editor only things like this who cares? 😏 

run:
ILMerge.exe /xmldocs /out:merged\NSubstitute.dll NSubstitute.dll Castle.Core.dll System.Threading.Tasks.Extensions.dll

Now only referencing 'NSubstitute.dll' is enough to make it work.

Thanks for sharing this repository with the world 😄

**Comment by Thundernerd** [comment]
My apologies, I completely missed this issue for more than a year it seems. I'll look into it!

**Comment by Thundernerd** [comment]
Fixed in v4.4.0!
