### ISSUE TITLE
v4.4.0 is not work for Play Mode tests

### ISSUE THREAD

**Issue by nowsprinting** [Thundernerd/Unity3D-NSubstitute#6]
I using this package in Play Mode tests assembly.

An error occurred when this upgrade package to v4.4.0:
```
error CS0246: The type or namespace name 'NSubstitute' could not be found (are you missing a using directive or an assembly reference?)
```

Version 4.4.0 was changed DLL wrapped assembly type changed from Runtime(any) to Editor.
I want the assembly back to the runtime.

refs https://github.com/nowsprinting/UnityTestExamples/pull/10

**Comment by Thundernerd** [comment]
Fixed with latest release: https://github.com/Thundernerd/Unity3D-NSubstitute/releases/tag/v5.1.0
